// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace hoangcam0256.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("hoangcam0256.Models.NHC256SanPham", b =>
                {
                    b.Property<int>("NHC256MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("NHC256Address")
                        .HasColumnType("REAL");

                    b.Property<string>("NHC256TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NHC256MaSanPham");

                    b.ToTable("NHC256SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
